#!/bin/sh

if [ -z $IPCCMD ]; then
	IPCCMD=duskc
fi

bind_settingsmenu() {
	JSON=$($IPCCMD get_settings | jq ".Functionality")
	NAME="wm"
	if [[ $(command -v wmctrl) != "" ]]; then
		NAME=$(wmctrl -m | awk '/Name:/ {print $2}')
	fi

	echo $JSON | jq '.' | awk -F":" -vNAME="$NAME" '
		BEGIN {
			print "#INDENT#" NAME
		}

		NF == 1 {
			next
		}

		{
			gsub(/^  |"|,/, "");
			print "#INDENT#	" $1 ": " $2 "\t #IPCCMD# run_command toggle \"" $1 "\""
		}
	' | sed -e "s/#INDENT#/$1/" -e "s/#IPCCMD#/${IPCCMD}/"
}

# Allow the above menu to be sourced by other scripts by setting
# the SOURCE_MENU environment variable.
if [ -z $SOURCE_MENU ]; then
	$(bind_settingsmenu | xmenu)
fi
