#!/bin/bash

test -z "$IPCCMD" && IPCCMD=duskc

bind_system() {
	cat << EOF | sed -e "s/#INDENT#/$1/" -e "s/#IPCCMD#/${IPCCMD}/"
#INDENT#System
#INDENT#	Logout	#IPCCMD# run_command quit
#INDENT#	Shutdown	sudo shutdown now
#INDENT#	Restart	shutdown -r now
EOF
}

# Suspend	systemctl suspend
# Hybrid Sleep    systemctl hybrid-sleep
# Hibernate   systemctl hibernate

# Allow the above menu to be sourced by other scripts by setting
# the SOURCE_MENU environment variable.
if [ -z "$SOURCE_MENU" ]; then
	eval "$(bind_system '' | xmenu)"
fi
