#!/bin/bash

# Defaults
EVENCOLOR="^C1^"
ODDCOLOR="^C1^"
TEXTCOLOR="^d^"
TBPAD=4
HEIGHT=$BAR_HEIGHT
TMPFILE="/tmp/.${USER}.statusbar.volume.${DISPLAY}.dat~"

if [ -f $TMPFILE ]; then
	source $TMPFILE
fi

while (( $# )); do
	case "$1" in
	-h|--height)
		shift
		HEIGHT=$1
		shift
		;;
	--evencolor)
		shift
		EVENCOLOR=$1
		shift
		;;
	--oddcolor)
		shift
		ODDCOLOR=$1
		shift
		;;
	--textcolor)
		shift
		TEXTCOLOR=$1
		shift
		;;
	--tbpad)
		shift
		TBPAD=$1
		shift
		;;
	esac
done

echo "EVENCOLOR='$EVENCOLOR';ODDCOLOR='$ODDCOLOR';TEXTCOLOR='$TEXTCOLOR';HEIGHT='$HEIGHT';TBPAD='$TBPAD'" > $TMPFILE

if [[ $(pacmd list-sinks | grep -c "muted: yes") > 0 ]]; then
	echo "🔇"
	exit
fi
VOLUME=$(pacmd list-sinks | awk '
	BEGIN {
		FOUND=0
	}
	/* index:/ {
		FOUND=1
	}
	/volume:/ {
		if (FOUND == 0)
			next
		gsub("%","",$5)
		print $5
		exit 0
	}
')
if [[ -z $VOLUME ]]; then
	echo " %"
	exit
fi

${HOME}/bin/statusbar/status2d_volume -p $VOLUME -h $HEIGHT --textcolor "$TEXTCOLOR" --oddcolor "$ODDCOLOR" --evencolor "$EVENCOLOR"
